USE [master]
GO

/****** Object:  Database [PM01_519_BARCHAS]    Script Date: 19.04.2023 16:21:54 ******/
CREATE DATABASE [PM01_519_BARCHAS]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PM01_519_BARCHAS', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\PM01_519_BARCHAS.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'PM01_519_BARCHAS_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\PM01_519_BARCHAS_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [PM01_519_BARCHAS] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [PM01_519_BARCHAS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [PM01_519_BARCHAS] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET ARITHABORT OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET  DISABLE_BROKER 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET  MULTI_USER 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [PM01_519_BARCHAS] SET DB_CHAINING OFF 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [PM01_519_BARCHAS] SET  READ_WRITE 
GO

